### ISSUE TITLE
Need feature

### ISSUE THREAD

**Issue by luxysiv** [peterlee0127/DNS-Security-iOS#2]
I need a feature which can add my owner nextdns server. Thanks!

**Comment by peterlee0127** [comment]
Got it. This feature may available within two weeks.

**Comment by luxysiv** [comment]
Thanks

**Comment by luxysiv** [comment]
And dark mode???

**Comment by peterlee0127** [comment]
Version 1.2 is now available in AppStore. 
Please try it!!

Dark mode is a minor feature, it may need more time to development.

**Comment by luxysiv** [comment]
Thanks, And I change 3 stars to 5 stars

**Comment by peterlee0127** [comment]
Hi, the version 1.3.0 will available in App Store soon. I already uploaded to App Store waiting for review today. (It needs two days)

It provides two type of rules. 
1. Only enable on selected SSID, others will disable.
2. Only disable on selected SSID, others will enable
<img src="https://user-images.githubusercontent.com/906325/97179614-fd4aad00-17d3-11eb-8fdd-b97072d21d08.PNG" width=250px>

It also bring the dark mode in this update. 

Hope you can enjoy it. It also welcome to share this app to the community. Thanks.

**Comment by luxysiv** [comment]
Yeah, I told some my friend but you should add some features. In appstore, DNSecure is same your app but it’s free

**Comment by luxysiv** [comment]
1 my friend bought your app
