### ISSUE TITLE
Enable WiFi only for specified SSID?

### ISSUE THREAD

**Issue by gregor-hh** [peterlee0127/DNS-Security-iOS#3]
Hello, 
At first I like your App verry well, great work!👍👍 

This is not an issue , its a feature request:

It would be very nice if it‘s possible to enable WiFi Mode only for specified WiFis or the option to exclude some WiFis SSIDs.

Example: At home I use my PiHole DNS and dont want to overide it..

Any chance that it can be implemented?

Best regards
Greg

**Comment by peterlee0127** [comment]
Thanks for reply.
This feature is possible. It may available in 1.3.
The version 1.2 is in development for support User to add custom configuration.

**Comment by peterlee0127** [comment]
Hi, the version 1.3.0 will available in App Store soon. I already uploaded to App Store waiting for review today. (It needs two days)

It provides two type of rules. 
1. Only enable on selected SSID, others will disable.
2. Only disable on selected SSID, others will enable
<img src="https://user-images.githubusercontent.com/906325/97179614-fd4aad00-17d3-11eb-8fdd-b97072d21d08.PNG" width=250px>

It also bring the dark mode in this update. 

Hope you can enjoy it. It also welcome to share this app to the community. Thanks.

**Comment by gregor-hh** [comment]
Hi Peter, 
that sound great! Thank You very much.

I will test it immediatly if available.

best regards
