### ISSUE TITLE
Maybe ipv6 leak?

### ISSUE THREAD

**Issue by gregor-hh** [peterlee0127/DNS-Security-iOS#4]
Hello Peter, me again.
I saw something strange.

I am currently using dot-cloudflare through celluar, see image:
![FC97AF1B-CD45-4E96-86B8-69DDB54FCB75](https://user-images.githubusercontent.com/25980675/97185059-e8542680-179f-11eb-8fd3-255f684b6d8e.png)

A test on dnsleaktest.com looks good. See image:
![877D55E0-0EE7-4020-915B-C8BF402543D9](https://user-images.githubusercontent.com/25980675/97185101-f6a24280-179f-11eb-896b-5ad0cdcc4656.png)

But when I open a shell (iSH) on the iPhone + nslookup an ipv6 DNS server is taken from my celluar provider. See image:
![915D4CEC-8730-406A-8946-7140D090799F](https://user-images.githubusercontent.com/25980675/97185230-19345b80-17a0-11eb-9f21-8d32e0530d04.jpeg)

Is this normal behavior? Maybe dot or doh is only used in Safari or „Browsers“ only in iOS?

Best regards

**Comment by peterlee0127** [comment]
Hi, 
DOH/DOT will work on system wide.
For cloudflare testing, you can use the official tool: https://1.1.1.1/help

I also get a strange result from iSH app. Maybe you can ask them ? Dose they use some proxy/dns settings in app ? 
https://github.com/ish-app/ish

**Comment by gregor-hh** [comment]
Hello,
Thank You for the detailed explanation.

I have another app (Net Analyzer) and apparently another function / method for DNS resolution is used there. The DNS servers passed by the Celluar Provoder are also used here per default.

So it seems that the app developers must first adjust to the new standard for resolve DNS querrys. 

Your App is fine👍👍 Thank You very much. It can be closed

best regards
