### ISSUE TITLE
How to delete existing servers?

### ISSUE THREAD

**Issue by zero0ID** [peterlee0127/DNS-Security-iOS#7]
The app is delivered with some configured DNS servers. How to remove those servers?
And how to edit added configurations?

**Comment by zero0ID** [comment]
Sorry I'm new here, didnt want to close the queston.

**Comment by peterlee0127** [comment]
Hi, zero0ID.
Thanks for using this app.
1. The default config can't be removed. They are default configs for free user.
2. If you are using unlock to pro version/ DNS Security Pro, you can add more configurations.

**Comment by zero0ID** [comment]
Hi Peter Lee,
thank you for reply.
I purchased the pro version and added my preferred Uncensored Unicast and Anycast DoT servers
(https://blog.uncensoreddns.org)

Additionally to TLS Pubkeys there are also newly integrated ECDSA keys and certificates, but this is something very new for me... I have to understand how this works and what are the pro's and con's.
(https://blog.uncensoreddns.org/blog/33-hello-to-dns-over-https-and-ecdsa-keys/)

One more detail, even the customer created entries cannot be edited, I have to delete the added server and create a new one. Swipe right - Edit?

Best

-0ID
-- 
Sent with Tutanota, the secure & ad-free mailbox: 
https://tutanota.com


3 Jan 2021, 07:10 by notifications@github.com:

**Comment by zero0ID** [comment]
Wondering if those "mandatory" and unremovable DNS servers have a secondary function too....

**Comment by peterlee0127** [comment]
Thanks for reply.
About this issue.
‘Wondering if those "mandatory" and unremovable DNS servers have a secondary function too....’
The current API in iOS 14 only support one config in a time. So if you already select another profile, the previous one will not be enabled. You can also check the current setting in status tab (third tab of app).

And the reminder for you, if the app use their own DNS resolve method (like ish...etc). The dns setting will not work in this app. The DNS_Settings in iOS 14 will work in “almost” all apps and system app.

https://developer.apple.com/documentation/networkextension/dns_settings
