### ISSUE TITLE
TLS Pubkey?

### ISSUE THREAD

**Issue by zero0ID** [peterlee0127/DNS-Security-iOS#8]
There are some DNS servers using TLS Pubkeys for authentication, how to use this?

**Comment by peterlee0127** [comment]
Thanks for using this app.

Currently, I implement this app using the iOS 14 API. https://developer.apple.com/videos/play/wwdc2020/10047/
It doesn't support adding TLS Pubkeys for authentication.
If you want to use this method, you can try to use there official app. like NextDNS, OpenVPN...etc.
